### ISSUE TITLE
What is the git_url for the hello world skill boilerplate ?

### ISSUE THREAD

**Issue by ronanb3** [Watson-Personal-Assistant/developer#26]
What is the git_url for the hello world skill boilerplate in the page https://watson-personal-assistant.github.io/developer/skill/build-skill/

**Comment by ronanb3** [comment]
I think it is https://github.com/Watson-Personal-Assistant/SkillBoilerplate

**Comment by troyibm** [comment]
Yes, that is correct @Ronanb3

**Comment by ronanb3** [comment]
I don't have access to the code, can someone update it?

**Comment by troyibm** [comment]
you mean the documentation? @Ronanb3   Luaithrenn will update it.

**Comment by luaithrenn** [comment]
Updated, thanks.  See https://watson-personal-assistant.github.io/developer/skill/build-skill/
