### ISSUE TITLE
404 Not Found on Watson Assistant service located in Germany 

### ISSUE THREAD

**Issue by georgibakken** [Watson-Personal-Assistant/developer#37]
When trying to launch the Watson Assistant service located in Germany, I get the following error message:

`404 Not Found: Requested route ('watson-assistant.eu-de.bluemix.net') does not exist.`

Launching a service located in UK works fine. I have also created a ticket as I know this might not be the correct place to report the issue.

**Comment by troyibm** [comment]
worked for me.  Maybe just a timing glitch?  I'm able to create a Watson Assistant (formerly Conversation) service in Germany location.

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/19195331/41667838-8c039afe-7473-11e8-87c1-daed46b8fba9.png">

**Comment by georgibakken** [comment]
Yes, sorry for not updating. It got resolved a bit later. Probably a timing glitch
