### ISSUE TITLE
Setting up logs to BX account

### ISSUE THREAD

**Issue by swallacertp** [Watson-Personal-Assistant/developer#9]
The doc states: Step 5 "Please use the value under Tenant Id (it looks similar to a02ad488f-a456-423c-3drsg348hcv8) to send the following in an email to your Watson Assistant support representative." There is no link to the email or way that I can see to send this information in to IBM.

**Comment by troyibm** [comment]
That's intentional as the beta participant should know there point of contact as we have no single point of contact to document in the docs (nor do we want that).  Getting access to WA is still done through a WA representative.
